# src/Par/KolektaBundle/Resources/config/doctrine/Account.orm.yml
Par\KolektaBundle\Entity\Account:
  type: entity
  table: account
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    valute_date:
      type: date
    record_input_date:
      type: date
    payin:
      type: float
      length: 255
    payout:
      type: float
      length: 255
    debts_id:
      type: integer
      length: 255
    user_id:
      type: integer
      length: 255
  manyToOne:
    debts:
      targetEntity: Debts
      inversedBy: accounts
      joinColumn:
        name: debts_id
        referencedColumnName: id
  lifecycleCallbacks:
      prePersist: [ setCreatedAtValue ]
      preUpdate: [ setUpdatedAtValue ]
