# src/Par/KolektaBundle/Resources/config/doctrine/Actors.orm.yml
Par\KolektaBundle\Entity\Actors:
  type: entity
  table: actors
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
      unique: true
  oneToMany:
    users:
      targetEntity: User
      mappedBy: actors