# src/Par/KolektaBundle/Resources/config/doctrine/Debts_type.orm.yml
Par\KolektaBundle\Entity\Debts_type:
  type: entity
  table: debts_type
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
      unique: true
  oneToMany:
    debts:
      targetEntity: Debts
      mappedBy: debts_type