# src/Par/KolektaBundle/Resources/config/doctrine/Equals.orm.yml
Par\KolektaBundle\Entity\Equals:
  type: entity
  table: equals
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
      unique: true
  oneToMany:
    user_equals:
      targetEntity: User_equals
      mappedBy: equals