# src/Par/KolektaBundle/Resources/config/doctrine/User_equals.orm.yml
Par\KolektaBundle\Entity\User_equals:
  type: entity
  table: user_equals
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    user_id:
      type: integer
      length: 255
    equals_id:
      type: integer
      length: 255
  manyToOne:
    user:
      targetEntity: User
      inversedBy: user_equals
      joinColumn:
        name: user_id
        referencedColumnName: id
    equals:
      targetEntity: Equals
      inversedBy: user_equals
      joinColumn:
        name: equals_id
        referencedColumnName: id